- .gitignore
> .gitignore 작성

- seminar-list.md
> 엄의섭 ios 세미나 신청합니다

- seminar-list.md
> 최주빈 iOS 세미나 신청합니다

- seminar-list.md
> 김수영 backend 세미나 신청합니다.

- seminar-list.md
Signed-off-by: ChrisLee02 <hdchris765@snu.ac.kr>
> 이하동 react 세미나 신청합니다

- seminar-list.md
> 이종현 backend 세미나 신청합니다

- seminar-list.md
> 한창희 backend 신청합니다

- seminar-list.md
> 조강현 backend 세미나 신청합니다.

- seminar-list.md
> 강지호 backend 신청합니다

- seminar-list.md
> 홍순범 backend 신청합니다

- seminar-list.md
> 박신홍 iOS 세미나 신청합니다.

- seminar-list.md
> 문보현 backend 세미나 신청합니다.

- seminar-list.md
> 이민준 backend 세미나 신청합니다

- seminar-list.md
> 권신영 backend 세미나 신청합니다

- seminar-list.md
> 이철민 backend 세미나 신청합니다

- seminar-list.md
android 세미나 수강 신청, react 및 backend 청강 신청합니다.
> 홍정현 android 세미나 신청합니다

- seminar-list.md
고계훈입니다.
수강할 세미나로 backend, 청강할 세미나로 android 신청합니다.
> 고계훈 backend 세미나 신청합니다

- seminar-list.md
iOS 세미나 수강, backend 세미나 청강 신청합니다.
> 안재우 iOS 세미나 신청합니다.

- seminar-list.md
> 신동섭 Backend 세미나 신청합니다.

- seminar-list.md
Reverts wafflestudio/19.5-rookies#181
> Revert "github id 오류 정정"

- seminar-list.md
두 줄 고쳐진 것 수정하는 법을 몰라 아예 다시 fork 해서 수정, 신청합니다
> 이재민 react 신청합니다

- seminar-list.md
> 홍용기 react 신청합니다.

- README.md
- react/seminar0/README.md
- react/seminar1/README.md
- react/seminar2/README.md
- react/seminar3/README.md
- react/seminar4/README.md
- react/seminar5/README.md
> Frontend 커리큘럼 작성

- django/seminar0/assignment0/README.md
과제 스펙과 스프레드시트가 불일치 하는 부분이 있어 변경합니다.
> Update assignment-0 Readme

- django/seminar2/assignment2/README.md
- django/seminar2/assignment2/user/models.py
- django/seminar2/assignment2/user/serializers.py
> 과제 2 명세 수정 약간

- django/seminar2/assignment2/README.md
> Fix django seminar2 README.md

- django/seminar3/tests_user.py
> minor fix on Factory

- django/seminar3/tests_user.py
> fix assignment3 skeleton
